### PR TITLE
docs: add section about `resolves` and removal of Promise unwrapping

### PR DESCRIPTION
**Pull request by sheremet-va**

### CODE REVIEW

**Comment by dubzzz** [comment]
I had this option: https://github.com/tinylibs/tinyspy/compare/main...dubzzz:return-src-p?expand=1

**Comment by dubzzz** [comment]
@sheremet-va My option passes all the tests without any need to change them.

**Comment by sheremet-va** [comment]
Vitest team decided to make that change at our last weekly, we are introducing `toHaveResolved` matcher to ease the migration with this.

**Comment by dubzzz** [comment]
> Your option has hidden bugs because it introduced uncaught exceptions that are hard to catch, this is how it worked before actually (see https://github.com/tinylibs/tinyspy/pull/14).

Not really... The error is caught in my case. The `.then` receives two functions including one never throwing as a second argument. I think there is no risk of unhandled or I miss something 🤔

**Comment by dubzzz** [comment]
The #14 is not the same: by throwing in the catch it causes an unhandled. In my case I never throw for the catch clause and thus there is no unhandled.

**Comment by sheremet-va** [comment]
> The #14 is not the same: by throwing in the catch it causes an unhandled. In my case I never throw for the catch clause and thus there is no unhandled.

I see. Still, it incorrectly stores the awaited result instead of the value that was actually returned by the function. I would expect a Promise to be in `calls.results` here:

```ts
let promise = 
const mock = fn(() => {
  promise = new Promise((resolve) => resolve(42))
  return promise
})
mock.results[0] === promise
await mock
mock.results[0] === promise
```

**Comment by dubzzz** [comment]
Do you mean something like: https://github.com/dubzzz/tinyspy/commit/deeec2d3c9b49a9485f8ee133aa0013290233841?

**Comment by sheremet-va** [comment]
> Do you mean something like: [dubzzz@deeec2d](https://github.com/dubzzz/tinyspy/commit/deeec2d3c9b49a9485f8ee133aa0013290233841)?

Yes

**Comment by sheremet-va** [comment]
> > Do you mean something like: [dubzzz@deeec2d](https://github.com/dubzzz/tinyspy/commit/deeec2d3c9b49a9485f8ee133aa0013290233841)?
> 
> Yes

Oh, no, sorry. I mean:

```ts
result.then(
    (r: any) => (state.resolves.push(r)),
    (e: any) => (state.rejects.push(e))
)
```

**Comment by dubzzz** [comment]
If we go for:

```js
result.then(
    (r: any) => (state.resolves.push(r)),
    (e: any) => (state.rejects.push(e))
)
```

There is a question we must answer:

> Let's consider the following case:
> 
> ```js
> const f = vi.fn(async (value) => {
>   return value === 0 ? promiseWaitingFor5secReturning0 : promiseWaitingFor0secReturning1;
> })
> f(0);
> f(1);
> ```
>
> I imagine we want: resolves: [0, 1] and not [1, 0] (its the order in which they resolve).

**Comment by sheremet-va** [comment]
Yeah, I would expect it to be resolved in the order they are called. This is how `Promise.all` returns its valued

**Comment by sheremet-va** [comment]
Another name would be `settled` or `settledResults` with `PromiseFulfilledResult` interface

**Comment by dubzzz** [comment]
I have a _fully_ working version with tests at https://github.com/tinylibs/tinyspy/compare/main...dubzzz:return-src-p?expand=1. Let me know if relevant for a PR or not.

**Comment by sheremet-va** [comment]
> I have a _fully_ working version with tests at [`main...dubzzz:return-src-p`?expand=1 (compare)](https://github.com/tinylibs/tinyspy/compare/main...dubzzz:return-src-p?expand=1). Let me know if relevant for a PR or not.

PR welcome :)

**Pull request merged**
