### PR TITLE
next in a row

### PR DESCRIPTION
**Pull request by sirenkovladd**
Added support to add multiple next

### CODE REVIEW

**Comment by sirenkovladd** [comment]
@tony-go fail because https://github.com/tinylibs/tinyspy/pull/39

**Review by sheremet-va — COMMENTED** [review]
Should we also update README?

**Comment by sirenkovladd** [comment]
It will be better, but right now I don't even see an example of using nextResult/nextError
I think it is necessary to open an issue for documentation

**Comment by sheremet-va** [comment]
> It will be better, but right now I don't even see an example of using nextResult/nextError
> I think it is necessary to open an issue for documentation

Then it is fine 👍🏻

**Review by sheremet-va — APPROVED** [review]

**Comment by sirenkovladd** [comment]
Are there any blocks for the merge?

**Comment by sirenkovladd** [comment]
@sheremet-va

**Pull request merged**
